name: Pull Request Checks
on: pull_request
jobs:
  Rust-tests-lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: make test
      - uses: webiny/action-conventional-commits@v1.3.0
